### ISSUE TITLE
Přenášení ČK do MODS

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/proarc#5]
Čárový kód z Alephu by se měl přenášet do MODS, ideálně přes OAI. Dopňování ČK by mělo být volitelné po nastavení v Proarcu.

**Comment by leiblix** [comment]
Toto je velmi podobné https://github.com/proarc/proarc/issues/411. Je to nejspíš záležitost konverzní šablony, nedělal bych to konfigurovatelné. 

Když už, tak  by mohla být konfigurovatelná celá šablona, tak jak to bylo v MEditoru.

**Comment by jkremlacek** [comment]
Změna šablony by neměla jak získat ČK, protože v odpovědi pole 996 není.

Poslán dotaz Tomáši Prachařovi, zda-li je možné pole 996 vypisovat i do výsledku dotazu na xservices.

Pokud to možné nebude, tak bude nutné rozšířit implementaci katalogu AlephXServer, aby do mods připisoval ČK pomocí volání operace item-data na xserver - zde bude nutné rozhodnout, jak přistupovat k dokumentům, od kterých je k dispozici více exemplářů (za předpokladu, že se ČK nemá přenášet u dokumentů, složených z podčástí, kde má každá podčást vlastní ČK, jak požadoval @zabak ).

**Comment by jkremlacek** [comment]
Do doby, než se vyřeší jak detekovat přívazky apod. označené vlastním ČK, se budou přenášet všechny ČK přiřazené k danému sysnu a zpracovatelé případné nevyhovující ČK vyřadí ze seznamu identifikátorů objektu v ProArc-u.
