### ISSUE TITLE
Automatizovat vytváření a import pole 856 do Alephu

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/proarc#7]
Toto těžko říct, v jaké fázi zpracování by se dělo. Proarc jako takový s Krameriem propojený není, tudíž po něm nemůžeme chtít, aby vytvářel linky do Krameria.. I když to je na diskuzi.

**Comment by jkremlacek** [comment]
Implementováno na konci zpracování dokumentu - po exportu mimo ProArc v rámci přípravy dat pro Imageserver a Krameria nástrojem [Merlin](https://github.com/jkremlacek/Merlin). 

Připraví se .csv soubor (obsahující sysno, bázi a odkaz), který si skript na straně Alephu stáhne a aktualizuje pomocí něj záznam daného dokumentu.

Momentálně probíhá testovací běh, kdy se skript na straně Alephu spouští ručně. Po testování bude skript spouštěn každých 15 minut.

**Comment by jkremlacek** [comment]
Testování bylo ukončeno. Aktualizace pole 856 probíhá automaticky v 15-ti minutových intervalech.
